data_transformation:
  outputs:
    dev:
      dataset: fictive_company_transformation
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /opt/airflow/dbt/bq_key.json
      location: US
      method: service-account
      priority: interactive
      project: mycenter-425712
      threads: 4
      type: bigquery
    ci:
      dataset: fictive_company_transformation_ci
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /opt/airflow/dbt/bq_key.json
      location: US
      method: service-account
      priority: interactive
      project: mycenter-425712
      threads: 4
      type: bigquery
    prod:
      dataset: fictive_company_transformation_prod
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /opt/airflow/dbt/bq_key.json
      location: US
      method: service-account
      priority: interactive
      project: mycenter-425712
      threads: 4
      type: bigquery
  target: dev